project 'BlueWallet.xcodeproj'

# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'BlueWallet' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  use_frameworks!

  # Pods for BlueWallet
# React Native requirements
pod 'yoga', path: '../node_modules/react-native/ReactCommon/yoga'
pod 'DoubleConversion', :podspec => '../node_modules/react-native/third-party-podspecs/DoubleConversion.podspec'
pod 'Folly', :podspec => '../node_modules/react-native/third-party-podspecs/Folly.podspec'
pod 'glog', :podspec => '../node_modules/react-native/third-party-podspecs/glog.podspec'
pod 'React', path: '../node_modules/react-native', :subspecs => [
  'Core',
  'cxxreact',
  'CxxBridge',
  'RCTText',
  'RCTNetwork',
  'RCTWebSocket', # needed for debugging
  'RCTActionSheet',
  'RCTAnimation',
  'RCTImage' ]

  pod 'RNWatch', :path => '../node_modules/react-native-watch-connectivity'
end
  target 'BlueWalletTests' do
    inherit! :search_paths
    # Pods for testing

end

target 'BlueWalletWatch' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  #  use_frameworks!
  # Pods for BlueWalletWatch

end

target 'BlueWalletWatch Extension' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  #  use_frameworks!
  pod 'EFQRCode', '~> 4.5.0'
  # Pods for BlueWalletWatch Extension

end
